### PR TITLE
confirm registration

### PR DESCRIPTION
**Pull request by dannyvassallo**
@eliotsykes the "Sign In" template doesn't render. when you click the sign in nav link it doesn't even respond to anything. I can't figure it out.

### CODE REVIEW

**Comment by eliotsykes** [comment]
Thanks @dannyvassallo. I've skimmed through the code in the PR and haven't seen anything standout yet. Trying it out locally now to replicate.

**Comment by eliotsykes** [comment]
Replicated it locally, digging in now to find out what's happening, will report back when I've got more.

**Comment by eliotsykes** [comment]
@dannyvassallo Just a minor directory rename needed from `sessions/` to `session/` in a couple of places.

Run these 2 `mv` commands:

``` bash
# Inside your-rails-app dir
$ mv client/app/pods/session{s,}

$ mv client/tests/unit/pods/session{s,}
```

Then try `bin/ember s` and see if you can see the sign in page.

**Comment by dannyvassallo** [comment]
@eliotsykes it works!

**Comment by dannyvassallo** [comment]
@eliotsykes I've actually noticed now after updating the app for phonegap on both mine and ericas phones and updating the CLI on my laptop and my work computer -- the app crashes the server as soon as it connects to download the assets... is this normal at this point?

**Comment by eliotsykes** [comment]
@dannyvassallo What's the output from this command:

``` bash
# Inside your-rails-app dir
npm ls connect-phonegap --global
```

If the version of connect-phonegap is 0.16.0 It may be to do with this issue/PR https://github.com/phonegap/connect-phonegap/pull/116 - fingers crossed it'll be merged soon.

If the connect-phonegap version is 0.16.0 we can investigate downgrading the phonegap installation to workaround this.

**Comment by dannyvassallo** [comment]
@eliotsykes 

This is my work machine:

/usr/local/lib
└─┬ phonegap@5.1.1-0.29.0
  └── connect-phonegap@0.16.1

**Comment by eliotsykes** [comment]
@dannyvassallo Ok connect-phonegap 0.16.1 has the issue too.

Try uninstalling phonegap and reinstalling with the last version that used connect-phonegap 0.15.0, which appears to be phonegap 5.0.0-0.27.1 looking at this package.json:

https://github.com/phonegap/phonegap-cli/blob/5.0.0-0.27.1/package.json

``` bash
# Uninstall global phonegap
npm uninstall -g phonegap

# Reinstall phonegap version that used connect-phonegap 0.15.0
npm install -g phonegap@5.0.0-0.27.1
```

**Comment by dannyvassallo** [comment]
@eliotsykes finished the new checkpoints!

**Comment by eliotsykes** [comment]
Awesome, looks good, feel free to merge this and start a new branch when the next chapters are ready. Bring up any questions in today's call.

**Pull request merged**
